# название
name: JavaScript test

# целевые события для запуска
# в данном случае это push и pull_request, в ветку main
on:
  push:
    branches: [ main ]
    paths:
      - JS/**
  pull_request:
    branches: [ main ]
    paths:
      - JS/**

# выполняемые действия
jobs:
  javascript-test:
    runs-on: ubuntu-latest
    
    # запускаются по шагам
    # name - название шага
    # в github actions будет выводиться название шага, и процессы
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install 🔧
        working-directory: ./JS
        run: npm install

      - name: Run Test 🔨
        working-directory: ./JS
        run: npm run test
