# название
name: TypeScript test

# целевые события для запуска
# в данном случае это push и pull_request, в ветку master
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# выполняемые действия
jobs:
  typescript-test:
    runs-on: ubuntu-latest
    
    # запускаются по шагам
    # name - название шага
    # в github actions будет выводиться название шага, и процессы
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install 🔧
        working-directory: ./TS
        run: npm install

      - name: Run Test 🔨
        working-directory: ./TS
        run: npm run test
