# название
name: Python test

# целевые события для запуска
# в данном случае это push и pull_request, в ветку main
on:
  push:
    branches: [ main ]
    paths:
      - Python/**
  pull_request:
    branches: [ main ]
    paths:
      - Python/**

# выполняемые действия
jobs:
  python-test:
    runs-on: ubuntu-latest
    
    # запускаются по шагам
    # name - название шага
    # в github actions будет выводиться название шага, и процессы
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2

    - name: Set up Python 3.9 🔧
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Test with unittest 🔨
      working-directory: ./Python
      run: |
        python -m unittest discover -s ./test
